import * as v from 'valibot';
import { onSiteHabitatBaselineSchema } from '../onSite/habitatBaseline';
import { onSiteHabitatCreationSchema } from '../onSite/habitatCreation';
import { onSiteHabitatEnhancementSchema } from '../onSite/habitatEnhancement';
import { onSiteHedgerowBaselineSchema } from '../onSite/hedgerowBaseline';
import { onSiteHedgerowCreationSchema } from '../onSite/hedgerowCreation';
import { onSiteHedgerowEnhancementSchema } from '../onSite/hedgerowEnhancement';
import { onSiteWatercourseBaselineSchema } from '../onSite/watercourseBaseline';
import { onSiteWatercourseCreationSchema } from '../onSite/watercourseCreation';
import { onSiteWatercourseEnhancementSchema } from '../onSite/watercourseEnhancement';
import { offSiteHabitatBaselineSchema } from '../offSite/habitatBaseline';
import { offSiteHabitatCreationSchema } from '../offSite/habitatCreation';
import { offSiteHabitatEnhancementSchema } from '../offSite/habitatEnhancement';
import { offSiteHedgerowBaselineSchema } from '../offSite/hedgerowBaseline';
import { offSiteHedgerowCreationSchema } from '../offSite/hedgerowCreation';
import { offSiteHedgerowEnhancementSchema } from '../offSite/hedgerowEnhancement';
import { offSiteWatercourseBaselineSchema } from '../offSite/watercourseBaseline';
import { offSiteWatercourseCreationSchema } from '../offSite/watercourseCreation';
import { offSiteWatercourseEnhancementSchema } from '../offSite/watercourseEnhancement';

export const parseOnSiteHabitatBaseline = (data: v.InferInput<typeof onSiteHabitatBaselineSchema>) => v.safeParse(onSiteHabitatBaselineSchema, data);
export const parseOnSiteHabitatCreation = (data: v.InferInput<typeof onSiteHabitatCreationSchema>) => v.safeParse(onSiteHabitatCreationSchema, data);
export const parseOnSiteHabitatEnhancement = (data: v.InferInput<typeof onSiteHabitatEnhancementSchema>) => v.safeParse(onSiteHabitatEnhancementSchema, data);
export const parseOnSiteHedgerowBaseline = (data: v.InferInput<typeof onSiteHedgerowBaselineSchema>) => v.safeParse(onSiteHedgerowBaselineSchema, data);
export const parseOnSiteHedgerowCreation = (data: v.InferInput<typeof onSiteHedgerowCreationSchema>) => v.safeParse(onSiteHedgerowCreationSchema, data);
export const parseOnSiteHedgerowEnhancement = (data: v.InferInput<typeof onSiteHedgerowEnhancementSchema>) => v.safeParse(onSiteHedgerowEnhancementSchema, data);
export const parseOnSiteWatercourseBaseline = (data: v.InferInput<typeof onSiteWatercourseBaselineSchema>) => v.safeParse(onSiteWatercourseBaselineSchema, data);
export const parseOnSiteWatercourseCreation = (data: v.InferInput<typeof onSiteWatercourseCreationSchema>) => v.safeParse(onSiteWatercourseCreationSchema, data);
export const parseOnSiteWatercourseEnhancement = (data: v.InferInput<typeof onSiteWatercourseEnhancementSchema>) => v.safeParse(onSiteWatercourseEnhancementSchema, data);
export const parseOffSiteHabitatBaseline = (data: v.InferInput<typeof offSiteHabitatBaselineSchema>) => v.safeParse(offSiteHabitatBaselineSchema, data);
export const parseOffSiteHabitatCreation = (data: v.InferInput<typeof offSiteHabitatCreationSchema>) => v.safeParse(offSiteHabitatCreationSchema, data);
export const parseOffSiteHabitatEnhancement = (data: v.InferInput<typeof offSiteHabitatEnhancementSchema>) => v.safeParse(offSiteHabitatEnhancementSchema, data);
export const parseOffSiteHedgerowBaseline = (data: v.InferInput<typeof offSiteHedgerowBaselineSchema>) => v.safeParse(offSiteHedgerowBaselineSchema, data);
export const parseOffSiteHedgerowCreation = (data: v.InferInput<typeof offSiteHedgerowCreationSchema>) => v.safeParse(offSiteHedgerowCreationSchema, data);
export const parseOffSiteHedgerowEnhancement = (data: v.InferInput<typeof offSiteHedgerowEnhancementSchema>) => v.safeParse(offSiteHedgerowEnhancementSchema, data);
export const parseOffSiteWatercourseBaseline = (data: v.InferInput<typeof offSiteWatercourseBaselineSchema>) => v.safeParse(offSiteWatercourseBaselineSchema, data);
export const parseOffSiteWatercourseCreation = (data: v.InferInput<typeof offSiteWatercourseCreationSchema>) => v.safeParse(offSiteWatercourseCreationSchema, data);
export const parseOffSiteWatercourseEnhancement = (data: v.InferInput<typeof offSiteWatercourseEnhancementSchema>) => v.safeParse(offSiteWatercourseEnhancementSchema, data);

