import { type Habitat } from "./types";

export const conditions = {
    "Cropland - Arable field margins cultivated annually": {
        "Condition Assessment N/A": 1,
    },
    "Cropland - Arable field margins game bird mix": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Arable field margins pollen and nectar": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Arable field margins tussocky": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Cereal crops": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Winter stubble": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Horticulture": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Intensive orchards": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Non-cereal crops": {
        "Condition Assessment N/A": 1 as const,
    },
    "Cropland - Temporary grass and clover leys": {
        "Condition Assessment N/A": 1 as const,
    },
    "Grassland - Traditional orchards": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Bracken": {
        "Condition Assessment N/A": 1 as const,
    },
    "Grassland - Floodplain wetland mosaic and CFGM": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Lowland calcareous grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Lowland dry acid grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Lowland meadows": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Modified grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Other lowland acid grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Other neutral grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Tall herb communities (H6430)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Upland acid grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Upland calcareous grassland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Grassland - Upland hay meadows": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Blackthorn scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Bramble scrub": {
        "Condition Assessment N/A": 1 as const,
    },
    "Heathland and shrub - Gorse scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Hawthorn scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Hazel scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Lowland heathland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Mixed scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Mountain heaths and willow scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Rhododendron scrub": {
        "Condition Assessment N/A": 1 as const,
    },
    "Heathland and shrub - Dunes with sea buckthorn (H2160)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Other sea buckthorn scrub": {
        "Condition Assessment N/A": 1 as const,
    },
    "Heathland and shrub - Willow scrub": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Heathland and shrub - Upland heathland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Aquifer fed naturally fluctuating water bodies": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - High alkalinity lakes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Low alkalinity lakes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Marl lakes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Moderate alkalinity lakes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Peat lakes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Ponds (priority habitat)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Ponds (non-priority habitat)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Reservoirs": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Temporary lakes ponds and pools (H3170)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Calaminarian grasslands": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Coastal sand dunes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Coastal vegetated shingle": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Ruderal/Ephemeral": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Tall forbs": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Inland rock outcrop and scree habitats": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Limestone pavement": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Maritime cliff and slopes": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Sparsely vegetated land - Other inland rock and scree": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Allotments": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Lakes - Ornamental lake or pond": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Artificial unvegetated, unsealed surface": {
        "N/A - Other": 0 as const,
    },
    "Urban - Bioswale": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Intensive green roof": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Built linear features": {
        "N/A - Other": 0 as const,
    },
    "Urban - Cemeteries and churchyards": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Developed land; sealed surface": {
        "N/A - Other": 0 as const,
    },
    "Urban - Other green roof": {
        "Condition Assessment N/A": 1 as const,
    },
    "Urban - Facade-bound green wall": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Ground based green wall": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Ground level planters": {
        "Condition Assessment N/A": 1 as const,
    },
    "Urban - Biodiverse green roof": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Introduced shrub": {
        "Condition Assessment N/A": 1 as const,
    },
    "Urban - Open mosaic habitats on previously developed land": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Rain garden": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Actively worked sand pit quarry or open cast mine": {
        "Condition Assessment N/A": 1 as const,
    },
    "Individual trees - Urban tree": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Sustainable drainage system": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Unvegetated garden": {
        "N/A - Other": 0 as const,
    },
    "Urban - Vacant or derelict land": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Bare ground": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Urban - Vegetated garden": {
        "Condition Assessment N/A": 1 as const,
    },
    "Wetland - Blanket bog": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Depressions on peat substrates (H7150)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Fens (upland and lowland)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Lowland raised bog": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Oceanic valley mire[1] (D2.1)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Purple moor grass and rush pastures": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Reedbeds": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Wetland - Transition mires and quaking bogs (H7140)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Felled": {
        "Good": 3 as const,
    },
    "Woodland and forest - Lowland beech and yew woodland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Lowland mixed deciduous woodland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Native pine woodlands": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Other coniferous woodland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Other Scot's pine woodland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Other woodland; broadleaved": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Other woodland; mixed": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Upland birchwoods": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Upland mixed ashwoods": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Upland oakwood": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Wet woodland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Woodland and forest - Wood-pasture and parkland": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Coastal lagoons - Coastal lagoons": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - High energy littoral rock": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - High energy littoral rock - on peat, clay or chalk": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Moderate energy littoral rock": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Moderate energy littoral rock - on peat, clay or chalk": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Low energy littoral rock": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Low energy littoral rock - on peat, clay or chalk": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Features of littoral rock": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Rocky shore - Features of littoral rock - on peat, clay or chalk": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral coarse sediment": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral mud": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral mixed sediments": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Coastal saltmarsh - Saltmarshes and saline reedbeds": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Coastal saltmarsh - Artificial saltmarshes and saline reedbeds": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral seagrass": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral seagrass on peat, clay or chalk": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral biogenic reefs - Mussels": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral biogenic reefs - Sabellaria": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Features of littoral sediment": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral coarse sediment": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral mud": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral sand": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral muddy sand": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral mixed sediments": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral seagrass": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Artificial littoral biogenic reefs": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral sand": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal sediment - Littoral muddy sand": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal hard structures - Artificial hard structures": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal hard structures - Artificial features of hard structures": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Intertidal hard structures - Artificial hard structures with integrated greening of grey infrastructure (IGGI)": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
    "Watercourse footprint - Watercourse footprint": {
        "N/A - Other": 0 as const,
    },
    "Individual trees - Rural tree": {
        "Good": 3 as const,
        "Fairly Good": 2.5 as const,
        "Moderate": 2 as const,
        "Fairly Poor": 1.5 as const,
        "Poor": 1 as const,
    },
}
