import * as v from 'valibot';

const sharedHabitatTypes = [
    "Arable field margins cultivated annually",
    "Arable field margins game bird mix",
    "Arable field margins pollen and nectar",
    "Arable field margins tussocky",
    "Cereal crops",
    "Winter stubble",
    "Horticulture",
    "Intensive orchards",
    "Non-cereal crops",
    "Temporary grass and clover leys",
    "Traditional orchards",
    "Bracken",
    "Floodplain wetland mosaic and CFGM",
    "Lowland calcareous grassland",
    "Lowland dry acid grassland",
    "Lowland meadows",
    "Modified grassland",
    "Other lowland acid grassland",
    "Other neutral grassland",
    "Tall herb communities (H6430)",
    "Upland acid grassland",
    "Upland calcareous grassland",
    "Upland hay meadows",
    "Blackthorn scrub",
    "Bramble scrub",
    "Gorse scrub",
    "Hawthorn scrub",
    "Hazel scrub",
    "Lowland heathland",
    "Mixed scrub",
    "Mountain heaths and willow scrub",
    "Rhododendron scrub",
    "Dunes with sea buckthorn (H2160)",
    "Other sea buckthorn scrub",
    "Willow scrub",
    "Upland heathland",
    "Aquifer fed naturally fluctuating water bodies",
    "Ornamental lake or pond",
    "High alkalinity lakes",
    "Low alkalinity lakes",
    "Marl lakes",
    "Moderate alkalinity lakes",
    "Peat lakes",
    "Ponds (priority habitat)",
    "Ponds (non-priority habitat)",
    "Reservoirs",
    "Temporary lakes ponds and pools (H3170)",
    "Calaminarian grasslands",
    "Coastal sand dunes",
    "Coastal vegetated shingle",
    "Ruderal/Ephemeral",
    "Tall forbs",
    "Inland rock outcrop and scree habitats",
    "Limestone pavement",
    "Maritime cliff and slopes",
    "Other inland rock and scree",
    "Allotments",
    "Artificial unvegetated, unsealed surface",
    "Bioswale",
    "Intensive green roof",
    "Built linear features",
    "Cemeteries and churchyards",
    "Developed land; sealed surface",
    "Other green roof",
    "Facade-bound green wall",
    "Ground based green wall",
    "Ground level planters",
    "Biodiverse green roof",
    "Introduced shrub",
    "Open mosaic habitats on previously developed land",
    "Rain garden",
    "Actively worked sand pit quarry or open cast mine",
    "Sustainable drainage system",
    "Unvegetated garden",
    "Vacant or derelict land",
    "Bare ground",
    "Vegetated garden",
    "Urban tree",
    "Rural tree",
    "Blanket bog",
    "Depressions on peat substrates (H7150)",
    "Fens (upland and lowland)",
    "Lowland raised bog",
    "Oceanic valley mire[1] (D2.1)",
    "Purple moor grass and rush pastures",
    "Reedbeds",
    "Transition mires and quaking bogs (H7140)",
    "Lowland beech and yew woodland",
    "Lowland mixed deciduous woodland",
    "Native pine woodlands",
    "Other coniferous woodland",
    "Other Scot's pine woodland",
    "Other woodland; broadleaved",
    "Other woodland; mixed",
    "Upland birchwoods",
    "Upland mixed ashwoods",
    "Upland oakwood",
    "Wet woodland",
    "Wood-pasture and parkland",
    "Coastal lagoons",
    "High energy littoral rock",
    "High energy littoral rock - on peat, clay or chalk",
    "Moderate energy littoral rock",
    "Moderate energy littoral rock - on peat, clay or chalk",
    "Low energy littoral rock",
    "Low energy littoral rock - on peat, clay or chalk",
    "Features of littoral rock",
    "Features of littoral rock - on peat, clay or chalk",
    "Saltmarshes and saline reedbeds",
    "Artificial saltmarshes and saline reedbeds",
    "Littoral coarse sediment",
    "Littoral mud",
    "Littoral mixed sediments",
    "Littoral seagrass",
    "Littoral seagrass on peat, clay or chalk",
    "Littoral biogenic reefs - Mussels",
    "Littoral biogenic reefs - Sabellaria",
    "Features of littoral sediment",
    "Artificial littoral coarse sediment",
    "Artificial littoral mud",
    "Artificial littoral sand",
    "Artificial littoral muddy sand",
    "Artificial littoral mixed sediments",
    "Artificial littoral seagrass",
    "Artificial littoral biogenic reefs",
    "Littoral sand",
    "Littoral muddy sand",
    "Artificial hard structures",
    "Artificial features of hard structures",
    "Artificial hard structures with integrated greening of grey infrastructure (IGGI)",
    "Watercourse footprint",
]

export const baselineHabitatType = v.picklist([
    ...sharedHabitatTypes,
    "Felled",
])
export type BaselineHabitatType = v.InferOutput<typeof baselineHabitatType>;

export const creationHabitatType = v.picklist(sharedHabitatTypes);
export type CreationHabitatType = v.InferOutput<typeof creationHabitatType>;

export const enhancedHabitatType = v.picklist([
    ...sharedHabitatTypes,
    "Replacement for felled woodland",
]);
export type EnhancedHabitatType = v.InferOutput<typeof enhancedHabitatType>;
